version: "3"
services:
  bitcorner-frontend:
    container_name: bitcorner-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      NODE_ENV: production
